### ISSUE TITLE
Current Volunteer Opportuniies on the home page link does not work

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/PeaceGeeks-Website#107]

**Comment by PeaceGeeks** [comment]
Correct text is as follows:
If you do not see a suitable opening above at this time, but still want to volunteer with PeaceGeeks, we encourage you to submit a General Application. If a suitable opportunity arises at a later date, our Talent Team will connect with you to schedule an interview.

**Comment by PeaceGeeks** [comment]
I have fixed it for now, but this change needs to be reflected in your local/ code or it will get overridden again

**Comment by reallyordinary** [comment]
Done.
