### ISSUE TITLE
Carefully read through all FAQs

### ISSUE THREAD

**Issue by nico-primak** [PeaceGeeksSociety/PeaceGeeks-Website#121]
For example, on the Amani page we see this:

What is Amani ?
Amani is a web platform developed by PeaceGeeks for international grassroots organizations working on the issues of peace, accountability and human rights.  The following are the typical steps to follow for an Amani implementation.

Ummm, please reread that last line. There are no steps to follow. If that is the answer then it has left me with more questions. Kind of counter intuitive to an FAQ page. 

Please read all questions and answers and make sure everything satisfies and that we are not missing information.

**Comment by PeaceGeeks** [comment]
fixed this one. Will ask shannon to review.
