### ISSUE TITLE
Tech Capacity (Projects or Partners) needs to be consistent on the Programs page

### ISSUE THREAD

**Issue by nico-primak** [PeaceGeeksSociety/PeaceGeeks-Website#125]
The blue button is labeled "TC Partners", the heading below says "TC Projects", the orange button is labeled "TC Projects", and the orange button links to the "Partners" page. 

See we know in the future this will point to the "Projects" page let's keep all the labelling to "TC Projects" and have the url point to the "Partners" page. I don't really think there is a lot of confusion there since the Partners page does contain TC info.

At a later date when the "Projects" page is ready we will only have to change the url.

**Comment by PeaceGeeks** [comment]
reverted to projects. you can fix the vast majority of these
