### ISSUE TITLE
Check that all testimonials have a name and organization

### ISSUE THREAD

**Issue by nico-primak** [PeaceGeeksSociety/PeaceGeeks-Website#126]
While looking through the site a saw a testimonial that was missing the name of the person.

The example that I saw was for Organisation Ecotouristique du Lac Oguemoué.

**Comment by PeaceGeeks** [comment]
added

**Comment by nico-primak** [comment]
Have all the other testimonials been checked? Maybe this is something to hand off to Shannon.
