### ISSUE TITLE
Add newsletter sign-up to footer

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/PeaceGeeks-Website#16]

**Comment by nico-primak** [comment]
Wait for design from Nico

**Comment by PeaceGeeks** [comment]
We at the very least need a button in the footer.

**Comment by nico-primak** [comment]
Revised footer design

https://drive.google.com/open?id=0B86cdZmwyts0VDJKWUprcFVjR3c

**Comment by nico-primak** [comment]
Noticed that this goes all the way back to ticket #4

**Comment by nico-primak** [comment]
As a temp fix a Newsletter link has been added to the footer. Ticket is still open.

**Comment by nico-primak** [comment]
Sign up form added. Still needs addition of privacy policy, social media icons, and copyright bar. See above link for details.

**Comment by nico-primak** [comment]
Approved, and closed.
