### ISSUE TITLE
Replace all font arrows with graphic arrow.

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/PeaceGeeks-Website#22]
Also, add the graphic arrow to any buttons that are missing the arrow. Nico to send graphic arrow to Chris in email.

**Comment by reallyordinary** [comment]
I didn't put arrows on front page latest project, latest news, latest event blocks because a) hashtags could overlap and b) it's pretty obvious those are clickable items.

**Comment by nico-primak** [comment]
Thanks Chris. I was pretty iffy on the arrows on the homepage but I thought this is the main landing page where we can introduce the arrows on a box to indicate a button, since most of our buttons are not standard size. 

Leaving arrows off on homepage buttons is OK.
