### ISSUE TITLE
Amani Admins should be able to edit all Banner Blocks

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/PeaceGeeks-Website#23]

**Comment by PeaceGeeks** [comment]
Add a new 'Manage Banner Blocks' option to the Config page
http://stage.geektheme.peacegeeks.org/admin/configure-amani

**Comment by nico-primak** [comment]
This should be on the Configure page as per above, but its fine for now. Will get Ben to make this change.
