### ISSUE TITLE
Supporters cards should flip. On flip side need text and url, click on url to open org page in new window.

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/PeaceGeeks-Website#33]
Example of how cards should work and look when they flip http://www.charitywater.org/about/contributors.php.

On the flip side will be PG Blue for the BG, some text to describe the sponsor and a url to their site that when clicked will open the page in a new window.

We really like the flipping action on the Charity Waters page. If this is not working with PG Blue please leave it as PG Soft Grey.

**Comment by reallyordinary** [comment]
No "flip" animation effect as such but they otherwise display as desired on hover. Note that only "Lush" seems to have any info to be displayed on hover currently.

**Comment by nico-primak** [comment]
This is a good first step for Phase 1. While the "flip" is a nice feature the way that it is set up now does show the back of card content. 

On that note, the back of card content looks to be placed on the bottom half of the card. Is it possible to have the content look more centred on the card?

**Comment by PeaceGeeks** [comment]
this looks good to me. I think Nico and I just need to get some content on this.
