### ISSUE TITLE
On 'Projects' - remove 'group by service' headers and replace with filters, as per mock

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/PeaceGeeks-Website#62]
for Past/ Current
users will be able to filter all projects using the filter from the design by four categories:
by project year 
by project service 
by partner country
by partner theme/ focus 

we will also apply infinite scroll once this is in place

**Comment by PeaceGeeks** [comment]
<img width="622" alt="screen shot 2015-09-18 at 10 44 42 pm" src="https://cloud.githubusercontent.com/assets/2263033/9974794/e113a4fc-5e56-11e5-963a-24fb9173e646.png">

**Comment by reallyordinary** [comment]
This is up but two things: 

1 - "Areas of Focus" entityreference is going to take a lot of work to turn it into a dropdown or checkboxes/radio buttons; it defaults to an autocomplete text field and has no other options. So I've left it off for now. 

2 - the expand/hide filters thing works, but has a bug - if you select any filter, it hides the filter area. Applies the filter, but hides the filter area. So... working on getting it to stop doing that.
