### ISSUE TITLE
Where can I manage content for 'Current openings' page? 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/PeaceGeeks-Website#74]
http://stage.geektheme.peacegeeks.org/currentopenings

**Comment by reallyordinary** [comment]
Those are just "Opportunity" content type items.

**Comment by nico-primak** [comment]
I am talking about the button and text at the bottom of the page. How do I edit that?

**Comment by reallyordinary** [comment]
Those are part of the View. http://stage.geektheme.peacegeeks.org/admin/structure/views/view/peace_geeks_opportunities/edit
