### ISSUE TITLE
Add 'Apply Now' below the copy for each current volunteer opportunity

### ISSUE THREAD

**Issue by nico-primak** [PeaceGeeksSociety/PeaceGeeks-Website#86]
If I am on the current openings page and I click to open 'Videographer' then at the bottom and above the hashtag keywords I would put the 'Apply Now' button.

If I closed that up and the clicked open the 'Graphic Designer' position then at the bottom of that copy I would see an 'Apply Now' button.

This would like to the current application form. At a later date we will develop a pre-populated form.

**Comment by PeaceGeeks** [comment]
Nico, as discussed a 'pre-polulated form' is nowhere close to being an option. An Apply Now button work address the curent U/X issue (currently there are postings and an 'Apply' button for General Applications for people who don't see a suitable position, but no 'Apply' option for people applying for one of the listed roles. Can we add a small 'Apply Now' button to all current postings which leads to the same page?

**Comment by nico-primak** [comment]
Hence that's why I said "at a later date we will develop a pre-populated form". As in for phase 2.
