### ISSUE TITLE
Links to external supporters pagers should open up a new window, and not take users away from PG

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/PeaceGeeks-Website#88]

**Comment by reallyordinary** [comment]
I'm not sure I understand what you mean. Uh... they do? Do that? Currently? If you click "visit website" it pops a new tab open with their site in it.

**Comment by nico-primak** [comment]
I think originally when we reviewed this section when we clicked on "visit website" it would open in the same window. 

It's opening in a new tab now, so that's OK.
